//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 money#10500:|
        ///computer:|name#我的电脑:| 的本地化字符串。
        /// </summary>
        internal static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 str#abc=abc:|
        ///str2#abc=abc/nflt=114514191980000/n:|abc=abc/nflt=114514191980000/n 的本地化字符串。
        /// </summary>
        internal static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 money#10500:|
        ///computer:|name#我的电脑:|
        ///flt#3141592600:|
        ///now#637994530277341822:| 的本地化字符串。
        /// </summary>
        internal static string test3 {
            get {
                return ResourceManager.GetString("test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 getsetint#10:|
        ///getsetDateTime#693937152000000000:|
        ///intlistgetset#20,40,60,80,100:|
        ///stringlistgetset#a:/!!/!|a,b/!idb,c/!!/!|/!!/!|c:|
        ///auto#test:|
        ///pubstr#pubtest:|
        ///db#3.1415926:|
        ///db2#3141592600:|
        ///tc:|getsetint#0:|getsetDateTime#694039104000000000:|intlistgetset#11,45,14,19,19:|stringlistgetset#/null:|auto#test:|pubstr#substring:|db#0:|db2#0:|tc#/null:|pubint#0:|intlist#/null:|intdict#1=2/n3=4/n5=6:|
        ///pubint#20:|
        ///intlist#10,20,30,40,50:|
        ///intdict:|1#2:|3#4:|5#6:| 的本地化字符串。
        /// </summary>
        internal static string test4 {
            get {
                return ResourceManager.GetString("test4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type#2:|
        ///Content#deflinename:/!|Name/idworkone:/!|Animat/idA_Start:/!|Type/idWork:/!|ModeType/idHappy:/!|&lt;Name&gt;k__BackingField/idworkone:/!|&lt;Animat&gt;k__BackingField/idA_Start:/!|&lt;Type&gt;k__BackingField/idWork:/!|&lt;ModeType&gt;k__BackingField/idHappy:/!|:|
        ///To#76561198267979020:| 的本地化字符串。
        /// </summary>
        internal static string test5 {
            get {
                return ResourceManager.GetString("test5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 deflinename:|EnableFunction#False:|Item#deflinename:/!|Type/idDrink:/!|name/id蒸馏水:/!|TranslateName/id蒸馏水:/!|Exp/id10:/!|Strength/id0:/!|StrengthFood/id0:/!|StrengthDrink/id140:/!|Feeling/id1:/!|Health/id-0.5:/!|Likability/id0:/!|Price/id16.5:/!|Desc/id最正宗的水，其实不合适长期饮用:/!|Description/id/n最正宗的水，其实不合适长期饮用:/!|DescriptionValues/id经验值=+10.00/!n口渴度=+140.00/!n心情=+1.00/!n健康=-0.50:/!|ImageSource/iddeflinename:/!!/!|:/!|Star/idFalse:/!|RealPrice/id16.122222222222224:/!|Graph/iddrink:/!|transname/id蒸馏水:/!|descs:/!|Image [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string test6 {
            get {
                return ResourceManager.GetString("test6", resourceCulture);
            }
        }
    }
}
